Repository AY2324S1-CS2103T-T09-1/tp, pull requests merged in 2023-10, with the labels that each got.

#89 Update UG for select event command
  build.gradle
  docs/UserGuide.md
Labels: documentation, type.Task

#90 Implement home command
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/HomeCommand.java
  src/main/java/seedu/address/logic/commands/event/SelectEventCommand.java
  src/main/java/seedu/address/logic/commands/tag/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/tag/DeleteTagCommand.java
  src/main/java/seedu/address/logic/commands/tag/ViewTagsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/EventContactDisplay.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/HomeCommandTest.java
  src/test/java/seedu/address/logic/commands/person/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/tag/AddTagCommandTest.java
  src/test/java/seedu/address/logic/commands/tag/DeleteTagCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: priority.High, type.Story

#96 Update UG and DG to include delete_event and add_task
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation, type.Task

#91 Update DG to contain select event command
  docs/DeveloperGuide.md
Labels: documentation, type.Task

#105 Update DG to reflect updated command words
  docs/DeveloperGuide.md
Labels: documentation

#134 Fix feature to allow proper display after deleting an event
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/event/DeleteEventCommand.java
  src/main/java/seedu/address/logic/commands/event/SelectEventCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/EventContactDisplay.java
Labels: bug
